#!/bin/sh

bspc config border_width         4
bspc config window_gap          12

#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
#bspc config paddingless_monocle  false

bspc config click_to_focus          true
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor false

bspc config normal_border_color  "#1D2426"
bspc config focused_border_color "#ff0000"

bspc monitor -d 01 02 03 04 05 06 07 08 09 10

#bspc rule -a Gimp desktop=^8 state=floating follow=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

$HOME/.config/bspwm/panel &
sxhkd -c $HOME/.config/bspwm/sxhkdrc &
