#! /bin/sh

PANEL_WM_NAME=bspwm_panel

if xdo id -a $PANEL_WM_NAME > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# panel ###############################################################
BAR_HEIGHT=18
BAR_FONT=-*-terminus-bold-*-*-*-16-*-*-*-*-*-*-*

PANEL_PLEX=/home/lipeter/.config/bspwm/panel_python
#PANEL_PLEX=/home/lipeter/.config/bspwm/panel_perl
#PANEL_PLEX="mawk -Wi -f /home/lipeter/.config/bspwm/panel_awk"
PANEL_FIFO=/tmp/panel

[ -e $PANEL_FIFO ] && rm PANEL_FIFO
mkfifo $PANEL_FIFO

$PANEL_PLEX < $PANEL_FIFO | lemonbar -f $BAR_FONT -g x$BAR_HEIGHT -n $PANEL_WM_NAME &

conky -c /home/lipeter/.config/bspwm/conky.conf > $PANEL_FIFO &
xtitle -sf 'T%s' > $PANEL_FIFO &
bspc subscribe report > $PANEL_FIFO &

bspc config top_padding $BAR_HEIGHT

#wid=$(xdo id -a "$PANEL_WM_NAME")
#tries_left=20
#while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
#	sleep 0.05
#	wid=$(xdo id -a "$PANEL_WM_NAME")
#	tries_left=$((tries_left - 1))
#done
#[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
