#! /bin/sh

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
  case $line in
    T*) 
        title="${line#?}"
        ;;
    n*) 
        sys="${line#?}"
        ;;
    W*) 
        wm="${line#?}"
        ;;
  esac
  printf "%s\n" "${wm} ${title} %{r}${sys}"
done
